package statemachine

import (
	"strings"
	"testing"
)

func generateOrFail(t *testing.T, source string) string {
	t.Helper()
	ast, err := Parse("x.sm", []byte(source))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if err := Validate("x.sm", ast); err != nil {
		t.Fatalf("validate: %v", err)
	}
	output, err := Generate(ast)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return string(output)
}

func TestGenerateBasic(t *testing.T) {
	output := generateOrFail(t, `
package: traffic
name: Light
transitions: {
    *Red + Tick = Green,
    Green + Tick = Yellow,
    Yellow + Tick = Red,
}
`)
	for _, want := range []string{
		"package traffic",
		"type LightState uint8",
		"LightStateRed LightState = iota",
		"func DefaultLightState() LightState",
		"return LightStateRed",
		"func (s LightState) ProcessEvent(event LightEvent) (LightState, bool)",
		"case LightStateGreen, true",
		"const LightDOT = `digraph",
		`"Red" [shape=doublecircle]`,
	} {
		if want == "case LightStateGreen, true" {
			if !strings.Contains(output, "return LightStateGreen, true") {
				t.Errorf("output missing %q\n%s", "return LightStateGreen, true", output)
			}
			continue
		}
		if !strings.Contains(output, want) {
			t.Errorf("output missing %q\n%s", want, output)
		}
	}
}

func TestGenerateNoNamePrefix(t *testing.T) {
	output := generateOrFail(t, `
package: foo
transitions: {
    *Idle + Start = Running,
    Running + Stop = Idle,
}
`)
	if !strings.Contains(output, "type State uint8") {
		t.Errorf("expected un-prefixed type State, got:\n%s", output)
	}
	if !strings.Contains(output, "type Event uint8") {
		t.Errorf("expected un-prefixed type Event, got:\n%s", output)
	}
	if !strings.Contains(output, "func DefaultState() State") {
		t.Errorf("expected DefaultState, got:\n%s", output)
	}
}

func TestGenerateWildcardSpecificPriority(t *testing.T) {
	output := generateOrFail(t, `
package: main
transitions: {
    *A + Go = B,
    B + Go = C,
    _ + Go = A,
}
`)
	if !strings.Contains(output, "case StateA:\n\t\tswitch event {\n\t\tcase EventGo:\n\t\t\treturn StateB, true") {
		t.Errorf("expected specific A+Go -> B before wildcard, got:\n%s", output)
	}
}

func TestGenerateInternalTarget(t *testing.T) {
	output := generateOrFail(t, `
package: main
transitions: {
    *Moving + Tick = _,
    Moving + Arrive = Idle,
}
`)
	if !strings.Contains(output, "return StateMoving, true") {
		t.Errorf("expected internal Tick to return StateMoving, got:\n%s", output)
	}
}

func TestGenerateValidEventsIncludesWildcard(t *testing.T) {
	output := generateOrFail(t, `
package: main
transitions: {
    *A + Go = B,
    B + Stop = A,
    _ + Reset = A,
}
`)
	if !strings.Contains(output, "stateAValidEvents             = []Event{EventGo, EventReset}") &&
		!strings.Contains(output, "stateAValidEvents = []Event{EventGo, EventReset}") {
		t.Errorf("expected stateAValidEvents to include EventGo and EventReset, got:\n%s", output)
	}
}

func TestGenerateProducesValidGoSource(t *testing.T) {
	output := generateOrFail(t, `
package: main
transitions: {
    *A + Go = B,
    B + Stop = A,
    A | B + Halt = Stopped,
    _ + Reset = A,
}
`)
	if !strings.Contains(output, "// Code generated by") {
		t.Errorf("expected DO NOT EDIT header")
	}
	// gofmt-clean output is the contract; Generate already ran format.Source.
	if strings.Contains(output, "\t\t\t\t") {
		t.Errorf("output appears un-formatted")
	}
}
