// Code generated by github.com/matthewjberger/statemachine; DO NOT EDIT.

package main

type LightState uint8

const (
	LightStateRed LightState = iota
	LightStateGreen
	LightStateYellow
)

func (s LightState) String() string {
	switch s {
	case LightStateRed:
		return "Red"
	case LightStateGreen:
		return "Green"
	case LightStateYellow:
		return "Yellow"
	}
	return "Unknown"
}

var AllLightStates = [...]LightState{LightStateRed, LightStateGreen, LightStateYellow}

type LightEvent uint8

const (
	LightEventTick LightEvent = iota
	LightEventReset
)

func (e LightEvent) String() string {
	switch e {
	case LightEventTick:
		return "Tick"
	case LightEventReset:
		return "Reset"
	}
	return "Unknown"
}

var AllLightEvents = [...]LightEvent{LightEventTick, LightEventReset}

func DefaultLightState() LightState {
	return LightStateRed
}

func (s LightState) ProcessEvent(event LightEvent) (LightState, bool) {
	switch s {
	case LightStateRed:
		switch event {
		case LightEventTick:
			return LightStateGreen, true
		}
	case LightStateGreen:
		switch event {
		case LightEventTick:
			return LightStateYellow, true
		}
	case LightStateYellow:
		switch event {
		case LightEventTick:
			return LightStateRed, true
		}
	}
	switch event {
	case LightEventReset:
		return LightStateRed, true
	}
	return s, false
}

var (
	lightStateRedValidEvents    = []LightEvent{LightEventTick, LightEventReset}
	lightStateGreenValidEvents  = []LightEvent{LightEventTick, LightEventReset}
	lightStateYellowValidEvents = []LightEvent{LightEventTick, LightEventReset}
)

func (s LightState) ValidEvents() []LightEvent {
	switch s {
	case LightStateRed:
		return lightStateRedValidEvents
	case LightStateGreen:
		return lightStateGreenValidEvents
	case LightStateYellow:
		return lightStateYellowValidEvents
	}
	return nil
}

const LightDOT = `digraph {
  rankdir=LR;
  node [shape=circle];
  "Red" [shape=doublecircle];
  "Red" -> "Green" [label="Tick"];
  "Green" -> "Yellow" [label="Tick"];
  "Yellow" -> "Red" [label="Tick"];
  "Red" -> "Red" [label="Reset"];
  "Green" -> "Red" [label="Reset"];
  "Yellow" -> "Red" [label="Reset"];
}`
