// Code generated by github.com/matthewjberger/statemachine; DO NOT EDIT.

package main

type State uint8

const (
	StateOff State = iota
	StateIdle
	StateMoving
	StateWaiting
	StateEmergencyStopped
)

func (s State) String() string {
	switch s {
	case StateOff:
		return "Off"
	case StateIdle:
		return "Idle"
	case StateMoving:
		return "Moving"
	case StateWaiting:
		return "Waiting"
	case StateEmergencyStopped:
		return "EmergencyStopped"
	}
	return "Unknown"
}

var AllStates = [...]State{StateOff, StateIdle, StateMoving, StateWaiting, StateEmergencyStopped}

type Event uint8

const (
	EventPowerOn Event = iota
	EventMoveTo
	EventTick
	EventArrive
	EventObstacleDetected
	EventObstacleClear
	EventEmergencyStop
	EventReset
	EventPowerOff
)

func (e Event) String() string {
	switch e {
	case EventPowerOn:
		return "PowerOn"
	case EventMoveTo:
		return "MoveTo"
	case EventTick:
		return "Tick"
	case EventArrive:
		return "Arrive"
	case EventObstacleDetected:
		return "ObstacleDetected"
	case EventObstacleClear:
		return "ObstacleClear"
	case EventEmergencyStop:
		return "EmergencyStop"
	case EventReset:
		return "Reset"
	case EventPowerOff:
		return "PowerOff"
	}
	return "Unknown"
}

var AllEvents = [...]Event{EventPowerOn, EventMoveTo, EventTick, EventArrive, EventObstacleDetected, EventObstacleClear, EventEmergencyStop, EventReset, EventPowerOff}

func DefaultState() State {
	return StateOff
}

func (s State) ProcessEvent(event Event) (State, bool) {
	switch s {
	case StateOff:
		switch event {
		case EventPowerOn:
			return StateIdle, true
		}
	case StateIdle:
		switch event {
		case EventMoveTo:
			return StateMoving, true
		case EventEmergencyStop:
			return StateEmergencyStopped, true
		}
	case StateMoving:
		switch event {
		case EventTick:
			return StateMoving, true
		case EventArrive:
			return StateIdle, true
		case EventObstacleDetected:
			return StateWaiting, true
		case EventEmergencyStop:
			return StateEmergencyStopped, true
		}
	case StateWaiting:
		switch event {
		case EventObstacleClear:
			return StateMoving, true
		case EventEmergencyStop:
			return StateEmergencyStopped, true
		}
	case StateEmergencyStopped:
		switch event {
		case EventReset:
			return StateIdle, true
		}
	}
	switch event {
	case EventPowerOff:
		return StateOff, true
	}
	return s, false
}

var (
	stateOffValidEvents              = []Event{EventPowerOn, EventPowerOff}
	stateIdleValidEvents             = []Event{EventMoveTo, EventEmergencyStop, EventPowerOff}
	stateMovingValidEvents           = []Event{EventTick, EventArrive, EventObstacleDetected, EventEmergencyStop, EventPowerOff}
	stateWaitingValidEvents          = []Event{EventObstacleClear, EventEmergencyStop, EventPowerOff}
	stateEmergencyStoppedValidEvents = []Event{EventReset, EventPowerOff}
)

func (s State) ValidEvents() []Event {
	switch s {
	case StateOff:
		return stateOffValidEvents
	case StateIdle:
		return stateIdleValidEvents
	case StateMoving:
		return stateMovingValidEvents
	case StateWaiting:
		return stateWaitingValidEvents
	case StateEmergencyStopped:
		return stateEmergencyStoppedValidEvents
	}
	return nil
}

const DOT = `digraph {
  rankdir=LR;
  node [shape=circle];
  "Off" [shape=doublecircle];
  "Off" -> "Idle" [label="PowerOn"];
  "Idle" -> "Moving" [label="MoveTo"];
  "Moving" -> "Moving" [label="Tick"];
  "Moving" -> "Idle" [label="Arrive"];
  "Moving" -> "Waiting" [label="ObstacleDetected"];
  "Waiting" -> "Moving" [label="ObstacleClear"];
  "Idle" -> "EmergencyStopped" [label="EmergencyStop"];
  "Moving" -> "EmergencyStopped" [label="EmergencyStop"];
  "Waiting" -> "EmergencyStopped" [label="EmergencyStop"];
  "EmergencyStopped" -> "Idle" [label="Reset"];
  "Off" -> "Off" [label="PowerOff"];
  "Idle" -> "Off" [label="PowerOff"];
  "Moving" -> "Off" [label="PowerOff"];
  "Waiting" -> "Off" [label="PowerOff"];
  "EmergencyStopped" -> "Off" [label="PowerOff"];
}`
